from __future__ import annotations

"""isa_cad/output/templates/__init__.py
Pre-built report templates."""

DECISION_REPORT_TEMPLATE = (
    "# ISA-CAD Architecture Review: {proposal_id}

"
    "**Decision:** {decision}
"
    "**Score:** {score:.2f}
"
    "**Output Mode:** {output_mode}

"
    "---

## Summary

{summary}

"
    "## Next Steps

{next_steps}

"
    "---
*Generated by ISA-CAD v0.5.3*
"
)

ESCALATION_NOTICE_TEMPLATE = (
    "## Human Review Required

"
    "**Escalation level:** {escalation_level}

"
    "### Reasons

{reasons}

"
    "### Available decisions

{options}

"
    "{deadline_hint}
"
)

ADR_STUB_TEMPLATE = (
    "# ADR-{number}: {title}

"
    "**Status:** Accepted with acknowledged risk
"
    "**Date:** {date}
"
    "**Proposal:** {proposal_id}

"
    "## Context

{context}

"
    "## Decision

{decision}

"
    "## Consequences

"
    "- Risk accepted by: {reviewer}
"
    "- Monitoring required: yes
"
    "- Review deadline: {review_deadline}
"
)

__all__ = ["DECISION_REPORT_TEMPLATE", "ESCALATION_NOTICE_TEMPLATE", "ADR_STUB_TEMPLATE"]
