from __future__ import annotations

from pydantic import Field

from .base import ISABaseModel
from .enums import HumanDecision


class HumanReviewRequest(ISABaseModel):
    """
    Structured escalation request generated by HumanReviewGateNode.
    Describes *why* a human is needed and which decisions are available.
    Section 8 — Human-in-the-Loop & Safety.
    """
    required: bool = False
    reasons: list[str] = Field(default_factory=list)
    escalation_level: str = Field(
        "info",
        description="'info' | 'warning' | 'critical'",
    )
    options: list[HumanDecision] = Field(
        default_factory=list,
        description="Decisions the human can take",
    )
    deadline_hint: str = Field(
        "",
        description="Optional timing guidance, e.g. 'refresh before final forecast'",
    )
