from __future__ import annotations

from pydantic import Field

from .base import ISABaseModel
from .enums import OptimizationGoal


class Recommendation(ISABaseModel):
    """
    A goal-driven architecture recommendation generated by SandboxRecommendationNode.
    Each recommendation is a concrete improvement suggestion derived from pipeline
    signals (reviewer findings, veto gate results, blast radius).
    Section 7 — Sandbox & Goal-Driven Recommendations.
    """
    id: str = Field(..., description="Stable slug, e.g. 'rec.lambda-migration'")
    title: str
    rationale: str = Field("", description="Why this recommendation was triggered")
    primary_goal: OptimizationGoal = Field(
        OptimizationGoal.BALANCED,
        description="The optimization goal this recommendation primarily serves",
    )
    goal_alignment: float = Field(
        0.5, ge=0.0, le=1.0,
        description="How well this recommendation aligns with the current optimization_goal",
    )
    trigger: str = Field("", description="Signal that triggered this recommendation")
    suggested_changes: list[str] = Field(
        default_factory=list,
        description="Concrete architecture changes to make",
    )
    expected_improvements: dict[str, str] = Field(
        default_factory=dict,
        description="Expected metric improvements, e.g. {'cost': '~20% reduction'}",
    )
